'use client'

import React, { useState, useRef, useEffect, useCallback } from 'react'
import { ScanLine, Camera, X, Wifi } from 'lucide-react'
import { Button } from '@/components/ui/button'

interface ScanBarProps {
  orderNumber: string
  items: Array<{ _id: string; area?: string; product: string }>
  onItemSelected: (itemId: string, label: string) => void
  /** Whether the Workshop tab is currently active (pauses scanner when false) */
  active: boolean
}

function parseQR(raw: string): Record<string, string> {
  const out: Record<string, string> = {}
  for (const line of raw.trim().split('\n')) {
    const i = line.indexOf(':')
    if (i > 0) out[line.substring(0, i).trim()] = line.substring(i + 1).trim()
  }
  return out
}

export function WorkshopScanBar({ orderNumber, items, onItemSelected, active }: ScanBarProps) {
  const [mode, setMode] = useState<'keyboard' | 'camera'>('keyboard')
  const [cameraActive, setCameraActive] = useState(false)
  const [cameraError, setCameraError] = useState<string | null>(null)
  const [flashState, setFlashState] = useState<'idle' | 'ok' | 'err'>('idle')
  const [flashMsg, setFlashMsg] = useState('')
  const [liveBuffer, setLiveBuffer] = useState('') // visible chars while scanner is typing

  const bufferRef = useRef('')
  const lastKeyRef = useRef(0)
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const cameraRef = useRef<any>(null)

  // ─── QR processing ────────────────────────────────────────────────────────
  const flash = (ok: boolean, msg: string) => {
    setFlashState(ok ? 'ok' : 'err')
    setFlashMsg(msg)
    setTimeout(() => setFlashState('idle'), 2800)
  }

  const processScan = useCallback((raw: string) => {
    setLiveBuffer('')
    const trimmed = raw.trim()

    // URL format — generated by new QR labels and workshop mini-QR
    if (trimmed.startsWith('http://') || trimmed.startsWith('https://')) {
      try {
        const url = new URL(trimmed)
        const itemId = url.searchParams.get('item')
        const matched = itemId ? items.find(i => i._id === itemId) : undefined
        if (!matched) { flash(false, 'Item not found in this order'); return }
        onItemSelected(matched._id, matched.area || matched.product)
        flash(true, `✓ ${matched.area || matched.product} selected`)
      } catch {
        flash(false, 'Could not parse QR code')
      }
      return
    }

    // Legacy plain-text KEY:VALUE format
    const fields = parseQR(trimmed)
    const scannedOrder = fields['ORDER']
    const scannedItemId = fields['ITEM_ID']
    const scannedArea = fields['AREA']

    if (!scannedOrder) { flash(false, 'Invalid QR — no ORDER field found'); return }
    if (scannedOrder !== orderNumber) { flash(false, `QR is for order ${scannedOrder}`); return }

    let matched = scannedItemId ? items.find(i => i._id === scannedItemId) : undefined
    if (!matched && scannedArea && scannedArea !== '—') matched = items.find(i => i.area === scannedArea)
    if (!matched && items.length === 1) matched = items[0]

    if (!matched) { flash(false, 'Item not found in this order'); return }

    onItemSelected(matched._id, matched.area || matched.product)
    flash(true, `✓ ${matched.area || matched.product} selected`)
  }, [orderNumber, items, onItemSelected])

  // ─── Global keyboard listener (no click/focus needed) ─────────────────────
  useEffect(() => {
    if (!active || mode !== 'keyboard') return

    const onKey = (e: KeyboardEvent) => {
      // Don't intercept when user is typing into a real input or select
      const el = document.activeElement
      const inInput =
        (el instanceof HTMLInputElement && el.type !== 'hidden') ||
        el instanceof HTMLSelectElement ||
        (el instanceof HTMLTextAreaElement)
      if (inInput) return

      const now = Date.now()
      // Gap > 500 ms with no buffer → treat as new scan (reset)
      if (now - lastKeyRef.current > 500 && !bufferRef.current) {
        bufferRef.current = ''
      }
      lastKeyRef.current = now

      if (e.key === 'Enter') {
        bufferRef.current += '\n'
      } else if (e.key === 'Backspace') {
        bufferRef.current = bufferRef.current.slice(0, -1)
        setLiveBuffer(bufferRef.current)
        return
      } else if (e.key.length === 1) {
        bufferRef.current += e.key
        // Show only the first meaningful field while scanner is typing
        setLiveBuffer(bufferRef.current.split('\n')[0].substring(0, 40))
      } else {
        return // ignore special keys (Shift, Arrow, etc.)
      }

      if (timerRef.current) clearTimeout(timerRef.current)
      timerRef.current = setTimeout(() => {
        const buf = bufferRef.current.trim()
        bufferRef.current = ''
        if (buf) processScan(buf)
      }, 220)
    }

    window.addEventListener('keydown', onKey)
    return () => {
      window.removeEventListener('keydown', onKey)
      if (timerRef.current) clearTimeout(timerRef.current)
    }
  }, [active, mode, processScan])

  // Stop scanning when tab becomes inactive
  useEffect(() => {
    if (!active) stopCamera()
  }, [active]) // eslint-disable-line react-hooks/exhaustive-deps

  // ─── Camera ────────────────────────────────────────────────────────────────
  const stopCamera = useCallback(async () => {
    if (cameraRef.current) {
      try { await cameraRef.current.stop() } catch {}
      try { cameraRef.current.clear() } catch {}
      cameraRef.current = null
    }
    setCameraActive(false)
  }, [])

  const startCamera = useCallback(async () => {
    setCameraError(null)
    try {
      const { Html5Qrcode } = await import('html5-qrcode')
      if (cameraRef.current) {
        try { await cameraRef.current.stop() } catch {}
        try { cameraRef.current.clear() } catch {}
      }
      const scanner = new Html5Qrcode('workshop-qr-reader')
      cameraRef.current = scanner
      await scanner.start(
        { facingMode: 'environment' },
        { fps: 10, qrbox: { width: 220, height: 220 }, aspectRatio: 1 },
        (text: string) => processScan(text),
        () => {}
      )
      setCameraActive(true)
    } catch (err: any) {
      const msg = String(err?.message || err)
      setCameraError(
        msg.toLowerCase().includes('permission')
          ? 'Camera permission denied — allow camera access in your browser and try again.'
          : 'Could not start camera. Make sure you\'re on HTTPS or localhost.'
      )
    }
  }, [processScan])

  useEffect(() => {
    if (mode === 'camera') startCamera()
    else stopCamera()
  }, [mode]) // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => () => { stopCamera() }, [stopCamera])

  // ─── Render ────────────────────────────────────────────────────────────────
  return (
    <div className="space-y-2.5">
      {/* Mode toggle */}
      <div className="flex items-center gap-1 bg-gray-100 dark:bg-gray-800 rounded-lg p-1 w-fit">
        <button
          onClick={() => setMode('keyboard')}
          className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all ${
            mode === 'keyboard'
              ? 'bg-white dark:bg-gray-700 shadow-sm text-gray-800 dark:text-white'
              : 'text-gray-500 dark:text-gray-400 hover:text-gray-700'
          }`}
        >
          <ScanLine className="h-3.5 w-3.5" />
          USB / Bluetooth Scanner
        </button>
        <button
          onClick={() => setMode('camera')}
          className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all ${
            mode === 'camera'
              ? 'bg-white dark:bg-gray-700 shadow-sm text-gray-800 dark:text-white'
              : 'text-gray-500 dark:text-gray-400 hover:text-gray-700'
          }`}
        >
          <Camera className="h-3.5 w-3.5" />
          Camera / Mobile
        </button>
      </div>

      {/* ── Keyboard / USB scanner status zone ── */}
      {mode === 'keyboard' && (
        <div className={`flex items-center gap-3 px-3 py-2.5 rounded-xl border-2 transition-all ${
          flashState === 'ok'  ? 'border-green-400 bg-green-50 dark:bg-green-900/20' :
          flashState === 'err' ? 'border-red-400   bg-red-50   dark:bg-red-900/20' :
          liveBuffer           ? 'border-amber-400 bg-amber-50 dark:bg-amber-900/10' :
                                 'border-dashed border-gray-300 bg-gray-50/60 dark:bg-gray-800/40'
        }`}>
          {/* Pulse dot */}
          <span className={`w-2 h-2 rounded-full flex-shrink-0 ${
            flashState === 'ok'  ? 'bg-green-500' :
            flashState === 'err' ? 'bg-red-500' :
            liveBuffer           ? 'bg-amber-500 animate-pulse' :
                                   'bg-gray-300 dark:bg-gray-600'
          }`} />

          {flashState !== 'idle' ? (
            <span className={`text-xs font-medium ${flashState === 'ok' ? 'text-green-700 dark:text-green-400' : 'text-red-700 dark:text-red-400'}`}>
              {flashMsg}
            </span>
          ) : liveBuffer ? (
            <span className="text-xs font-mono text-amber-700 dark:text-amber-400 truncate">{liveBuffer}…</span>
          ) : (
            <span className="text-xs text-gray-500 dark:text-gray-400">
              Scanner ready — just scan a label. No click needed.
            </span>
          )}
        </div>
      )}

      {/* ── Camera / mobile scanner ── */}
      {mode === 'camera' && (
        <div className="rounded-xl border border-gray-200 dark:border-gray-700 overflow-hidden">
          <div id="workshop-qr-reader" className="w-full bg-black" />

          {cameraError && (
            <div className="p-3 bg-red-50 dark:bg-red-900/20 space-y-2">
              <p className="text-xs text-red-600 dark:text-red-400">{cameraError}</p>
              <Button size="sm" variant="outline" onClick={startCamera} className="text-xs h-7">Retry</Button>
            </div>
          )}

          {cameraActive && (
            <div className="flex items-center justify-between px-3 py-2 bg-gray-900">
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-green-400 animate-pulse" />
                <span className="text-xs text-gray-300">Camera active — point at QR label</span>
              </div>
              <button onClick={() => setMode('keyboard')} className="text-gray-400 hover:text-white">
                <X className="h-4 w-4" />
              </button>
            </div>
          )}

          {flashState !== 'idle' && (
            <div className={`px-3 py-2 text-xs font-medium border-t ${
              flashState === 'ok' ? 'bg-green-50 border-green-300 text-green-700' : 'bg-red-50 border-red-300 text-red-700'
            }`}>
              {flashMsg}
            </div>
          )}
        </div>
      )}
    </div>
  )
}
